version: '3'
services:
  drinkmorewatermain:
    build: ./drinkmorewatermain.Dockerfile
    volumes:
      user-config: /usr/drinkmorewaterbot/reminders
  drinkmorewaterrimind:
    build: ./drinkmorewaterremind.Dockerfile
    volumes:
      user-config: /usr/drinkmorewaterbot/reminders

volumes:
  user-config: ./reminders