services:
  drinkmorewatermain:
    restart: always
    image: marcomaschauer/drinkmorewaterreminderbot:latest
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"
  drinkmorewaterremind:
    restart: always
    image: marcomaschauer/drinkmorewaterreminderbot:latest
    command: [ "python3", "reminder.py" ]
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"