services:
  nginx:
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drinkmorewater.rule=Host(`drinkmorewater.marcom.one`)"
    networks:
      - "traefik_web"

networks:
  traefik_web:
    external: true
