version: '3'
services:
  drinkmorewatermain:
    build:
      context: .
      dockerfile: ./drinkmorewatermain.Dockerfile
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"
  drinkmorewaterrimind:
    build:      
      context: .
      dockerfile: ./drinkmorewaterremind.Dockerfile
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"