version: '3'
services:
  drinkmorewatermain:
    image: marcomaschauer/drinkmorewaterreminderbot:latest  
    build:
      context: .
      dockerfile: ./drinkmorewatermain.Dockerfile
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"
  drinkmorewaterremind:
    image: marcomaschauer/drinkmorewaterreminderbot:latest  
    build:   
      context: .
      dockerfile: ./drinkmorewaterremind.Dockerfile
    volumes:
      - "./reminders:/usr/drinkmorewaterbot/reminders:delegated"